version: '3.8'

services:
  backend:
    ports:
      - "80:8080"
    build: .
    depends_on:
     - postgres
    links:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/exchange_api
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  postgres:
    build: ./sql
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: exchange_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
